name: Refresh repository with current OAS files

# Run workflow for every push to the `main` branch
on:
  workflow_dispatch:

jobs:
  Refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Download OAS files
        run: |
          wget https://publishing.aspenft.io/api/v1/spec.json -O aspenpublishing.json

      - name: Update repository
        run: |
          git config user.email "oas@aspenft.io"
          git config user.name "OAS"
          git add *
          git commit -m "OAS Update"
          git push

      # Run GitHub Action to sync OpenAPI file at [path-to-file.json]
      - name: Update Readme.io
        # We recommend specifying a fixed version, i.e. @7.4.0
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@7.4.0
        with:
          rdme: openapi aspenpublishing.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.API_DEFINITION_ID }}
