name: Refresh repository with current OAS files

# Run workflow for every push to the `main` branch
on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *" # Every 15 mins

jobs:
  Refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Download OAS files
        run: |
          curl -s https://publishing.aspenft.io/api/v1/spec.json |jq -M '. |= . + {"servers":[{"url": "https://publishing.aspenft.io/"}]}' > aspenpublishing.json
          curl -s https://identity.aspenft.io/api/v1/spec.json |jq -M '. |= . + {"servers":[{"url": "https://publishing.aspenft.io/"}]}' > identity.json

      - name: Update repository
        run: |
          git config user.email "oas@aspenft.io"
          git config user.name "OAS"
          git add *
          git diff-index --quiet HEAD || git commit -m "OAS Update"
          git diff-index --quiet HEAD || git push origin master

      # # Run GitHub Action to sync OpenAPI file at [path-to-file.json]
      # - name: Update Readme.io - Identity
      #   # We recommend specifying a fixed version, i.e. @7.4.0
      #   # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
      #   uses: readmeio/rdme@7.4.0
      #   with:
      #     rdme: openapi identity.json --key=${{ secrets.README_API_KEY }} --id=IDENTITY

      # Run GitHub Action to sync OpenAPI file at [path-to-file.json]
      - name: Update Readme.io - Publishing
        # We recommend specifying a fixed version, i.e. @7.4.0
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@7.4.0
        with:
          rdme: openapi aspenpublishing.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.API_DEFINITION_ID }}
