name: Refresh repository with current OAS files

# Run workflow for every push to the `main` branch
on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Download OAS files
        run: |
          wget https://publishing.aspenft.io/api/v1/spec.json -O aspenpublishing.json

      - name: Update repository
        run: |
          git add *
          git commit -m "OAS Update"
          git push
